[package]
name = "gpui_wgpu"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "Apache-2.0"

[lints]
workspace = true

[lib]
path = "src/gpui_wgpu.rs"

[features]
default = []
test-support = ["dep:image", "gpui/test-support"]

[dependencies]
gpui.workspace = true
anyhow.workspace = true
image = { workspace = true, optional = true }
collections.workspace = true
log.workspace = true
parking_lot.workspace = true
fontique = "0.11.0"
parley = "0.11.0"
skrifa = "0.43.2"
raw-window-handle = "0.6"
gpui_util.workspace = true
wgpu.workspace = true
vello = "0.9.0"
vello_svg = { git = "https://github.com/linebender/vello_svg", rev = "2db0427e4dc9879bd636caf69e60dee026d83699", default-features = false }
usvg.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
pollster.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation.workspace = true
core-video.workspace = true

[target.'cfg(target_family = "wasm")'.dependencies]
wasm-bindgen.workspace = true
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["HtmlCanvasElement"] }
js-sys = "0.3"

[dev-dependencies]
criterion.workspace = true
gpui = { workspace = true, features = ["test-support"] }
image.workspace = true
smallvec.workspace = true

[[bench]]
name = "layout_line"
harness = false
